cd .\Publish\
cd .\LabCMS.Gateway.Server\
start LabCMS.Gateway.Server.exe
cd ..\LabCMS.ProjectDomain.Server\
start LabCMS.ProjectDomain.Server.exe
cd ..\LabCMS.FixtureDomain.Server\
start LabCMS.FixtureDomain.Server.exe
cd ..\LabCMS.EquipmentDomain.Server\
start LabCMS.EquipmentDomain.Server.exe