// <auto-generated />
using System;
using LabCMS.EquipmentDomain.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabCMS.EquipmentDomain.Server.Migrations.UsageRecordsRepositoryMigrations
{
    [DbContext(typeof(UsageRecordsRepository))]
    [Migration("20200928134908_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("LabCMS.EquipmentDomain.Shared.Models.UsageRecord", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
