// <auto-generated />
using LabCMS.FixtureDomain.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabCMS.FixtureDomain.Server.Migrations
{
    [DbContext(typeof(FixturesRepository))]
    [Migration("20200923133734_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("LabCMS.FixtureDomain.Shared.Models.Fixture", b =>
                {
                    b.Property<string>("ProjectNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectNo", "Type", "SortId", "Direction");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("LabCMS.FixtureDomain.Shared.Models.Fixture", b =>
                {
                    b.OwnsOne("LabCMS.FixtureDomain.Shared.Models.LocationNo", "LocationNo", b1 =>
                        {
                            b1.Property<string>("FixtureProjectNo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FixtureType")
                                .HasColumnType("TEXT");

                            b1.Property<int>("FixtureSortId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FixtureDirection")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Floor")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StockNo")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FixtureProjectNo", "FixtureType", "FixtureSortId", "FixtureDirection");

                            b1.ToTable("Fixtures");

                            b1.WithOwner()
                                .HasForeignKey("FixtureProjectNo", "FixtureType", "FixtureSortId", "FixtureDirection");
                        });

                    b.Navigation("LocationNo");
                });
#pragma warning restore 612, 618
        }
    }
}
