// <auto-generated />
using LabCMS.ProjectDomain.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabCMS.ProjectDomain.Server.Migrations
{
    [DbContext(typeof(ProjectsRepository))]
    [Migration("20201122121902_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LabCMS.ProjectDomain.Shared.Models.Project", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("No");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
